version: '3.8'

services:
  app:
    container_name: bizkos
    build: .
    ports:
      - "9002:9002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXT_PUBLIC_NODE_ENV=${NEXT_PUBLIC_NODE_ENV}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - db

  db:
    container_name: bizkos-db
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - private-net
volumes:
  pgdata:
networks:
  private-net:
    external: true
