version: '3.8'

services:
  app:
    container_name: bizkos
    build: .
    ports:
      - "9002:9002"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: bizkos-db
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
networks:
  - default
volumes:
  pgdata:
networks:
  default:
